[package]
name = "fluid2d_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
# ndarray = "0.15.6"

[profile.release]
lto = true
